app/feature/forms.py
"""
WTForms used for Featured Stories
"""
from flask_wtf import FlaskForm
from wtforms import (
    SubmitField,
    TextAreaField,
    RadioField
)
from wtforms.validators import (
    DataRequired
)


class FeaturedStoryForm(FlaskForm):
    """
    The WTForm used to create a new featured story
    """
    left_right = RadioField("Picture on Left or Right", choices=[('left', "Picture on Left Side"), ('right', "Picture on Right Side")],
                            validators=[DataRequired()], default='left')
    quote = TextAreaField("Insert a quote here", validators=[DataRequired()])
    submit = SubmitField('Submit')


class ModifyFeatureForm(FlaskForm):
    """
    The WTForm used to create a new featured story
    """
    left_right = RadioField("Picture on Left or Right", choices=[('True', "Picture on Left Side"),
                                                                 ('False', "Picture on Right Side")],
                            validators=[DataRequired()], default='left')

    quote = TextAreaField("Insert a quote here", validators=[DataRequired()])

    is_visible = RadioField("Visibility", choices=[('True', "Visible"), ('False', "Not Visible")],
                            validators=[DataRequired()], default='True')

    submit = SubmitField('Submit')

app/feature/__init__.py
from flask import Blueprint

feature = Blueprint('feature', __name__)

from . import views

app/feature/views.py
"""
View functions for story functionality
"""
from flask import render_template, request, flash, redirect, url_for
from flask_login import current_user, login_required

from app.constants.event import EDIT_FEATURED_STORY
from app.db_utils import create_object, update_object
from app.feature import feature
from app.feature.forms import FeaturedStoryForm, ModifyFeatureForm
from app.feature.utils import create_featured_story, update_featured_story, hide_current_featured_story
from app.models import Events, FeaturedStories, Stories


@feature.route('/', methods=['GET'])
@login_required
def listing():
    """
    View function for the feature page. The feature page contains all the featured stories.
    This function queries the database for all the featured stories.

    :return: renders the 'feature.html' template with featured story list
    """
    featured_stories = FeaturedStories.query.filter_by().all()

    return render_template('feature/feature.html', featured_stories=featured_stories)


@feature.route('/<story_id>', methods=['GET', 'POST'])
@login_required
def set_featured_story(story_id):
    """
    View function for adding a story to featured stories.
    This function provides an interface for stories that are being featured for the first time.
    In POST request, if all the fields are validated, then it will redirect user to the home page

    :return: first time register a story to featured story renders 'add.html'
                if inputs are validated, redirect to main page 'main.index'
    """
    add_featured_form = FeaturedStoryForm(request.form)
    story = Stories.query.filter_by(id=story_id).one_or_none()

    if request.method == 'POST':
        if add_featured_form.validate_on_submit():
            new_quote = add_featured_form.quote.data.strip("\"")
            create_featured_story(story=story,
                                  left_right=add_featured_form.left_right.data,
                                  quote=new_quote)
            flash("Story is now Featured!", category='success')
            return redirect(url_for('main.index'))
        else:
            for field, error in add_featured_form.errors.items():
                flash(add_featured_form.errors[field][0], category='danger')
            return render_template('feature/add.html', form=add_featured_form, story=story)

    else:
        featured_story = FeaturedStories.query.filter_by(story_id=story_id).one_or_none()
        if featured_story is not None:
            hide_current_featured_story()
            update_object({"is_visible": True}, FeaturedStories, featured_story.id)
            create_object(Events(
                _type=EDIT_FEATURED_STORY,
                story_id=featured_story.story_id,
                user_guid=current_user.guid,
                previous_value={"is_visible": False},
                new_value={"is_visible": True}
            ))
            flash("Story is now Featured!", category='success')
            return redirect(url_for('main.index'))
        return render_template('feature/add.html', form=add_featured_form)


@feature.route('/modify/<story_id>', methods=['GET', 'POST'])
@login_required
def modify(story_id):
    """
    This view function is used for modifying/editing the featured story.
    Modifying attributes such as left/right image location, visibility, and quote.

    :param story_id: the story_id you would like to modify. this story_id must be in FeaturedStories table
    :return: renders 'modify.html' that contains the form for modifying existing featured story
                if all the form inputs are validated, it redirects users to the main page 'main.index'
    """
    featured_story = FeaturedStories.query.filter_by(story_id=story_id).one_or_none()
    form = ModifyFeatureForm(request.form, left_right=featured_story.left_right, quote=featured_story.quote,
                             is_visible=featured_story.is_visible)
    story = Stories.query.filter_by(id=story_id).one_or_none()

    if request.method == 'POST':
        if form.validate_on_submit():
            new_quote = form.quote.data.strip("\"")
            update_featured_story(featured_story=featured_story,
                                  left_right=form.left_right.data,
                                  quote=new_quote,
                                  is_visible=form.is_visible.data)
            flash("Story is now Modified!", category='success')
            return redirect(url_for('main.index'))

    else:
        if featured_story is None:
            flash("This story does not exist in Featured Story", category='danger')
            return redirect(url_for('feature.listing'))
    return render_template('feature/modify.html', story=story, form=form)

app/templates/feature/add.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="page-header col-md-6 col-md-offset-3">
    <h1 id="feature-header">Add to Featured Stories</h1>
</div>
<div class="col-md-6 col-md-offset-3">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/feature/feature.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="page-header col-md-4 col-md-offset-4">
    <h1 id="feature-header">Featured Stories</h1>
</div>


<div class="col-md-10 col-md-offset-1">
    <table class="table table-hover">
        <thead>
            <tr>
            <th scope="col"></th>
            <th scope="col">Story ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Left or Right</th>
            <th scope="col">Visibility</th>
            <th scope="col">Quote</th>
            </tr>
        </thead>
        <tbody>
        <!-- Remember that story_list contains a list of tuples -->
        {% for featured_story in featured_stories %}
            <tr>
              <th scope="row">
                <a class="icon" href="{{ url_for('feature.modify', story_id=featured_story.story_id) }}" title="Edit Record">
                    <span class="fa fa-pencil glyphicon glyphicon-pencil"></span>
                </a>
              </th>
              <td>{{ featured_story.story_id }}</td>
              <td>{{ featured_story.story.activist_first }}</td>
              <td>{{ featured_story.story.activist_last }}</td>
              <td>
                  {% if featured_story.left_right == True %}
                    Left
                  {% else %}
                    Right
                  {% endif %}
              </td>
              <td>{{ featured_story.is_visible }}</td>
              <td>{{ featured_story.quote }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/feature/modify.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="page-header col-md-6 col-md-offset-3">
    <h1 id="feature-header">Modify this Featured Story</h1>
</div>
<div class="col-md-6 col-md-offset-3">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/feature/rank.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="page-header col-md-4 col-md-offset-4">
        <h3 id="feature-header">Current Rankings of the Featured Stories</h3>
    </div>

    <div class="container-fluid" id="view-story-container">
         <div class="col-md-offset-1 col-md-10 col-md-offset-1">
            <table id="rankTable" class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Rank</th>
                        <th scope="col">Move</th>
                        <th scope="col">Story ID</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Quote</th>
                    </tr>
                </thead>
                <tbody>
                {#         Remember that story_list contains a list of tuples       #}
                {% for story in story_list %}
                    <tr onclick="rowName(this)">
                        <td>{{ story[1].rank }}</td>
                        <th scope="row">
                            <input type="button" value="up" class="move up" />
                            <input type="button" value="down" class="move down" />
                        </th>
                        <td value={{ story[0].id }}>{{ story[0].id }}</td>
                        <td>{{ story[0].activist_first }}</td>
                        <td>{{ story[0].activist_last }}</td>
                        <td>{{ story[1].quote }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div id="view-edit-delete-div">
        <form method="post">
            {{ form.csrf_token }}
            <input class="btn btn-default btn-lg" id="view-edit-delete-btn" value="Rerank this Featured Story" name="submit" type="submit">
        </form>
    </div>

{% endblock %}

{% block custom_script %}
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/feature/rank.js') }}"></script>
{% endblock %}